{{- define "mychart.labels" }}
  labels:
    project: sample
    app: demo
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-02
  {{- template "mychart.labels" }}
data:
  x: 100
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- end }}


# .Values inside the loop, Need to change that to $.Values
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-02
  {{- template "mychart.labels" }}
data:
  x: 100
  {{- with .Values.favorite }}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | upper | quote }}
  {{- end }}

