{{ if .Values.cm.enabled | default false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-02
data:
{{- if eq (int .Values.my_number) 100 }}
  my_number_if: {{ quote .Values.my_number }}
{{- end }}
  x: 2000
{{ end }}
